-- Audit Country Plan table.
CREATE TABLE [dbo].[AuditDetailedActivities]
(
    [AuditDetailedActivityId] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [AuditLogRowStatus]       INT             NOT NULL,
    [DetailedActivityId]      INT             NOT NULL,
    [StrategicActionId]       INT             NOT NULL,
    [Description]             NVARCHAR (1000) NULL,
    [StartDate]               DATETIME2 (7)   NULL,
    [EndDate]                 DATETIME2 (7)   NULL,
    [ImplementationStatus]    INT             NOT NULL,
    [Feasibility]             INT             NOT NULL,
    [Impact]                  INT             NOT NULL,
    [Priority]                INT             NOT NULL,
    [Source]                  INT             NULL,
    [RiskName]                NVARCHAR (1000) NULL,
    [RiskLevel]               INT             NULL,
    [Deadline]                NVARCHAR (1000) NULL,
    [Responsible]             NVARCHAR (1000) NULL,
    [ResponsibleAuthority]    NVARCHAR (MAX)  NULL,
    [InstituteId]             INT             NULL,
    [CostAssumptions]         NVARCHAR (1000) NULL,
    [EstimatedCost]           FLOAT (53)      NULL,
    [FundAvailability]        BIT             NULL,
    [EstimatedBudgetSource]   NVARCHAR (1000) NULL,
    [ExistingBudget]          FLOAT (53)      NULL,
    [FinancialGap]            FLOAT (53)      NULL,
    [NeedTechnicalAssistance] BIT             NULL,
    [NeedFinancialAssistance] BIT             NULL,
    [DonorContribution]       FLOAT (53)      NULL,
    [Donor]                   NVARCHAR (1000) NULL,
    [ActualCost]              FLOAT (53)      NULL,
    [Comments]                NVARCHAR (1000) NULL,
    [CreatedAt]               DATETIME2 (7)   NOT NULL,
    [CreatedBy]               INT             NOT NULL,
    [LastUpdatedAt]           DATETIME2 (7)   NOT NULL,
    [LastUpdatedBy]           INT             NOT NULL
);
